# Generated by Django 4.2.1 on 2023-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_rename_vote_skipvote_suggestedsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedsong',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
