# Generated by Django 4.2.1 on 2023-05-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_votes_to_suggest_song'),
        ('spotify', '0004_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='SkipVote',
        ),
        migrations.CreateModel(
            name='SuggestedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('img', models.CharField(max_length=150)),
                ('spotify_id', models.CharField(max_length=150)),
                ('votes', models.IntegerField(default=0)),
                ('task_id', models.CharField(max_length=50, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
