# Generated by Django 4.2.1 on 2023-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='votes_to_suggest_song',
            field=models.IntegerField(default=1),
        ),
    ]
