# Generated by Django 4.2.1 on 2023-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_votes_to_suggest_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='votes_to_suggest_song',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
